image: docker:latest
services:
   - docker:dind

variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE

before_script:
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}

build:
   stage: build
   script:
     - docker pull $CONTAINER_IMAGE:latest || true
     - docker build --cache-from $CONTAINER_IMAGE:latest -t $CONTAINER_IMAGE:latest .
     - docker push $CONTAINER_IMAGE:latest
   only:
     - master
