image: docker:latest
services:
   - docker:dind

variables:
  CI_DEBUG_TRACE: "true"
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

before_script:
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}

build:
   stage: build
   script:
     - docker build -f $(pwd)/Dockerfile.$CI_COMMIT_TAG -t $IMAGE_TAG .
     - docker push $IMAGE_TAG
   only:
     - tags
